xcodeproj 'FishLampCore.xcodeproj'

platform :ios, '7.0'

target :"FishLampCore-iOS-ARC" do
    platform :ios, '7.0'
end

target :"FishLampCore-OSX-32-MRC" do
    platform :osx, '10.6'
end

target :"FishLampCore-OSX-64-MRC" do
    platform :osx, '10.6'
end

target :"FishLampCore-OSX-64-ARC" do
    platform :osx, '10.6'
end

target :"FishLampCore-OSX-Universal-MRC" do
    platform :osx, '10.6'
end